@url = http://localhost:5001/api/budgets
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzU5MzIyZWE3Y2MyYjFlZmYwYzBjMmYiLCJpYXQiOjE3MzM4OTkxNzEsImV4cCI6MTczMzk4NTU3MX0.wdjDtR0ipQQdTnKNJ88shLolaSm6I8KOvZVHPQNeHXM
@id=6759bb53e16c9f3114ceedda

GET {{url}}/user
Authorization: bearer {{token}}

###Get all budget
GET {{url}}
Authorization: bearer {{token}}

###Get a budget by id
GET {{url}}/{{id}}
Authorization: bearer {{token}}

###Create a budget
POST {{url}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "category":"Food",
    "name":"fast food",
    "total_amount":5000,
    "month":"December",
    "year":2024
}

### Edit amount of a budget by id
PATCH {{url}}/{{id}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "total_amount":2500
}

### Remove amount of a budget
DELETE {{url}}/{{id}}
Authorization: bearer {{token}}