@url = http://localhost:5001/api/expenses
@id = 675a5ff77bd0303358e41715
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzU5Y2JlOTdiZDAzMDMzNThlNDE1ZDUiLCJpYXQiOjE3MzM5NzY4NjMsImV4cCI6MTczNDA2MzI2M30.7skqA6iniJJSf3ClkyaRHtf5a1EbHNnWQabc_Yq6ZEg
@budget_id=6759cc937bd0303358e41637

### Get all expenses
GET {{url}}
Authorization: bearer {{token}}

### Get all expenses of a particular user
GET {{url}}/user
Authorization: bearer {{token}}

### Get expense by id
GET {{url}}/{{id}}
Authorization: bearer {{token}}

### Get expense by budget id
GET {{url}}/budget/{{budget_id}}
Authorization: bearer {{token}}

### Create Expense
POST {{url}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name":"Hotel",
    "budget":"Varanasi",
    "amount":1000
}

### Update Expense
PATCH {{url}}/{{id}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name":"Bus",
    "amount":1500
}

### Remove Expense by id
DELETE {{url}}/{{id}}
Authorization: bearer {{token}}